### ISSUE TITLE
SpringCloudGateway路由配置说明

### ISSUE THREAD

**Issue by LonelymoonWang** [LonelymoonWang/blog#2]
### 配置路由和网关

配置predicates和filters有两种方法：等号关联和键值对。

#### 等号关联

shortcuts由过滤器名称识别，过滤器名称紧跟`=`符号，并在等号后编写具体的参数值，如果有多个参数值，则按逗号`,`隔开。

如以下示例所示，在spring.cloud.gateway.routes后添加列表，列表是键值对形式，有id、uri、predicates，配置predicates的值也是列表，列表中的值以等号分隔键值对，如下，predicates配置了Cookie=mycookie,mycookievalue的断言，Cookie代表着属性，等号的mycookie后面代表的是这个属性中的每个键，并且紧跟逗号后添上的mycookievalue是这个键匹配的值。

```yml
spring:
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: https://example.org
        predicates:
        - Cookie=mycookie,mycookievalue
```

#### 键值对

如示例所示，在配置predicates的值时，有第二种方式，即在此列表中设置name、args属性，args属性中又设置name、regexp属性；predicates后的name代表的是属性，args中的name和regexp代表的是键和键对应匹配的值。

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: https://example.org
        predicates:
        - name: Cookie
          args:
            name: mycookie
            regexp: mycookievalue
```

#### The After Route Predicate Factory

匹配发生在某时间之后的请求

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: https://example.org
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]

```

#### The Before Route Predicate Factory

匹配发生在某时间之前的请求

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: before_route
        uri: https://example.org
        predicates:
        - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
```

#### The Between Route Predicate Factory

匹配某时间段之间的的所有请求

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: between_route
        uri: https://example.org
        predicates:
        - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
```

#### The Cookie Route Predicate Factory

匹配Cookie属性中对应的键值关系，

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: cookie_route
        uri: https://example.org
        predicates:
        - Cookie=chocolate, ch.p
```

#### The Header Route Predicate Factory

匹配请求头Header属性对应的键值关系

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: header_route
        uri: https://example.org
        predicates:
        - Header=X-Request-Id, \d+

```

#### The Host Route Predicate Factory

匹配主机名的列表，可以使用模板引擎，来获取二级域名的前缀，例如`{sub}.myhost.org`

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: https://example.org
        predicates:
        - Host=**.somehost.org,**.anotherhost.org
```

#### The Method Route Predicate Factory

匹配请求methods（GET、POST、DELETE、PUT）的参数，它是一个或多个参数

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: method_route
        uri: https://example.org
        predicates:
        - Method=GET,POST
```

#### The Path Route Predicate Factory

匹配请求的路径，但是这里有一个可选的配置，名叫“`matchTrailingSlash`”，默认为true，当设置成false的时候，类似`/red/1` 、 `/red/1/` 、 `/red/blue` 、 `/blue/green`这些请求路径格式的不会拦截。

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: https://example.org
        predicates:
        - Path=/red/{segment},/blue/{segment}
```

#### The Query Route Predicate Factory

匹配查询参数.

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: query_route
        uri: https://example.org
        predicates:
        - Query=green
```

如果想为查询参数设置值，请在查询参数后以逗号隔开并添加值。

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: query_route
        uri: https://example.org
        predicates:
        - Query=red, gree.
```

#### The RemoteAddr Route Predicate Factory

匹配IP地址和子网掩码

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: remoteaddr_route
        uri: https://example.org
        predicates:
        - RemoteAddr=192.168.1.1/24
```

#### The Weight Route Predicate Factory

匹配权重

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: weight_high
        uri: https://weighthigh.org
        predicates:
        - Weight=group1, 8
      - id: weight_low
        uri: https://weightlow.org
        predicates:
        - Weight=group1, 2
```

#### The XForwarded Remote Addr Route Predicate Factory

匹配最初发起请求的客户端的IP地址和子网掩码

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: xforwarded_remoteaddr_route
        uri: https://example.org
        predicates:
        - XForwardedRemoteAddr=192.168.1.1/24
