### ISSUE TITLE
SpringCloudGateway网关过滤器配置

### ISSUE THREAD

**Issue by LonelymoonWang** [LonelymoonWang/blog#3]
路由筛选器允许以某种方式修改传入的HTTP请求或传出的HTTP响应。路由筛选器的作用域为特定路由。Spring Cloud Gateway包括许多内置网关过滤器工厂。

#### The `AddRequestHeader` `GatewayFilter` Factory

添加请求头。

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: add_request_header_route
        uri: https://example.org
        filters:
        - AddRequestHeader=X-Request-red, blue
```

可以匹配对应的Host或者Path，如下：

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: add_request_header_route
        uri: https://example.org
        predicates:
        - Path=/red/{segment}
        filters:
        - AddRequestHeader=X-Request-Red, Blue-{segment}
```

#### The `AddRequestParameter` `GatewayFilter` Factory

添加请求参数过滤器

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: add_request_parameter_route
        uri: https://example.org
        filters:
        - AddRequestParameter=red, blue
```

可以匹配Host或者Path：

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: add_request_parameter_route
        uri: https://example.org
        predicates:
        - Host: {segment}.myhost.org
        filters:
        - AddRequestParameter=foo, bar-{segment}
```

#### The `AddResponseHeader` `GatewayFilter` Factory

添加响应头过滤器

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: add_request_header_route
        uri: https://example.org
        filters:
        - AddRequestHeader=X-Request-red, blue
```

可以匹配Host或者Path

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: add_response_header_route
        uri: https://example.org
        predicates:
        - Host: {segment}.myhost.org
        filters:
        - AddResponseHeader=foo, bar-{segment}
```

#### The `DedupeResponseHeader` `GatewayFilter` Factory

删除响应头过滤器

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: dedupe_response_header_route
        uri: https://example.org
        filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
```

#### Spring Cloud CircuitBreaker GatewayFilter Factory

‎Spring Cloud CircuitBreaker GatewayFilter 工厂使用 Spring Cloud CircuitBreaker API 将网关路由包装在断路器中。Spring Cloud CircuitBreaker支持多个可与Spring Cloud Gateway一起使用的库。Spring Cloud支持开箱即用的Resilience4J。‎

如果想用Spring Cloud CircuitBreaker filter，那么必须将`spring-cloud-starter-circuitbreaker-reactor-resilience4j`依赖添加到依赖库中。以下是CircuitBreaker的配置：

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: circuitbreaker_route
        uri: https://example.org
        filters:
        - CircuitBreaker=myCircuitBreaker
```

要配置断路器，请参阅正在使用的基础断路器实现的配置。文档地址[Spring Cloud Circuit Breaker](https://cloud.spring.io/spring-cloud-circuitbreaker/reference/html/spring-cloud-circuitbreaker.html)

‎Spring Cloud CircuitBreaker 过滤器也可以接受可选参数‎`fallbackUri`。目前，仅支持`forward:`。如果调用回退，则请求将转发到与 URI 匹配的控制器。下面的示例配置此类回退：

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: circuitbreaker_route
        uri: lb://backing-service:8088
        predicates:
        - Path=/consumingServiceEndpoint
        filters:
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/inCaseOfFailureUseThis
        - RewritePath=/consumingServiceEndpoint, /backingServiceEndpoint
```

这段配置也可以使用Java代码进行配置：

```java
@Bean
public RouteLocator routes(RouteLocatorBuilder builder) {
    return builder.routes()
        .route("circuitbreaker_route", r -> r.path("/consumingServiceEndpoint")
            .filters(f -> f.circuitBreaker(c -> c.name("myCircuitBreaker").fallbackUri("forward:/inCaseOfFailureUseThis"))
                .rewritePath("/consumingServiceEndpoint", "/backingServiceEndpoint")).uri("lb://backing-service:8088")
        .build();
}
```

当断路器回退被调用时，这个例子转发给/inCaseofFailureUse这个URI。注意，这个示例还演示了(可选的)Spring Cloud LoadBalancer负载均衡(由目标URI上的lb前缀定义)。

主要的场景是使用fallbackUri在网关应用程序中定义内部控制器或处理程序。然而，你也可以在外部应用程序中将请求重新路由到控制器或处理器，如下所示:

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: ingredients
        uri: lb://ingredients
        predicates:
        - Path=//ingredients/**
        filters:
        - name: CircuitBreaker
          args:
            name: fetchIngredients
            fallbackUri: forward:/fallback
      - id: ingredients-fallback
        uri: http://localhost:9994
        predicates:
        - Path=/fallback
```

在本例中，没有在网关程序中处理fallback，而是由网关转发到了localhost:9994所在的程序中，并在该程序实现了fallback接口。

在请求被转发到callback接口的情况下，Spring Cloud CircuitBreaker Gateway filter也提供了Throwable。它作为ServerWebExchangeUtils添加到ServerWebExchange。我们还可以在网关应用程序内处理回退时使用CIRCUITBREAKER_EXECUTION_EXCEPTION_ATTR属性

对于外部控制器/处理程序场景，可以添加带有异常细节的头。可以参考FallbackHeaders GatewayFilter Factory。

##### Tripping The Circuit Breaker On Status Codes

在某些情况下，我们在处理fallback接口的时候，不想跳转到其他的接口，而是直接返回状态码和具体的描述信息，可以采用如下方式：

```yaml
spring:
  cloud:
    gateway:
      routes:
      - id: circuitbreaker_route
        uri: lb://backing-service:8088
        predicates:
        - Path=/consumingServiceEndpoint
        filters:
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/inCaseOfFailureUseThis
            statusCodes:
              - 500
              - "NOT_FOUND"
```

对应的Java代码实现：

```java
@Bean
public RouteLocator routes(RouteLocatorBuilder builder) {
    return builder.routes()
        .route("circuitbreaker_route", r -> r.path("/consumingServiceEndpoint")
            .filters(f -> f.circuitBreaker(c -> c.name("myCircuitBreaker").fallbackUri("forward:/inCaseOfFailureUseThis").addStatusCode("INTERNAL_SERVER_ERROR"))
                .rewritePath("/consumingServiceEndpoint", "/backingServiceEndpoint")).uri("lb://backing-service:8088")
        .build();
}
